name: cloud_user
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.0

  # Networking & API
  dio: ^5.4.0
  socket_io_client: ^3.0.0

  # Navigation
  go_router: ^13.0.0

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.3
  google_sign_in: ^6.2.1

  # Maps & Location
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

  # UI & Assets
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0

  # Storage & Utils
  shared_preferences: ^2.2.0
  uuid: ^4.2.2
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  visibility_detector: ^0.4.0+2
  youtube_player_iframe: ^5.2.2
  lottie: ^3.3.2
  image_picker: ^1.2.1
  webview_flutter: ^4.13.1
  video_player: ^2.10.1
  chewie: ^1.13.0
  carousel_slider: ^5.1.1
  flutter_local_notifications: ^19.5.0
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Generators
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#FFFFFF"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/icons/laundry.png
    - assets/images/icons/dry_cleaning.png
    - assets/images/icons/shoe_cleaning.png
    - assets/images/icons/leather_cleaning.png
    - assets/images/icons/curtain_cleaning.png
    - assets/images/icons/carpet_cleaning.png
